import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'



export default function Home() {
  return (
    <>
      <Head>
        <title>Lottery Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <div className={styles.landing}>
            <div className={styles.navbar}>
              <h1>LotteryDApp</h1>
              <ul>
                <li>Home</li>
                <li>Players</li>
                <li>Lottery History</li>
              </ul>
              <button>Connect Wallet</button>
            </div>

            <div className={styles.center}>
              <h1>Enter Lottery and Win</h1>
              <h3>With just 10 USDC, you stand a chance of winning $90 and other cool prizes</h3>
              <button>Get Started!</button>
            </div>
            
          </div>
      </main>
    </>
  )
}
